"""agent threads and messages

Durable conversations, so an agent run survives a page reload and can be
reopened from the Agent screen.

SAFETY: purely additive. Two new tables, no ALTER against anything that
already holds data, no backfill, no data movement. The foreign keys point
*out* at tenants/channels/outliers/users/outlier_diagnoses; no existing
table gains a column or a constraint. Running this against the live
database cannot touch the 21,138 CEMEX rows.

`agent_messages.diagnosis_id` references the existing `outlier_diagnoses`
row rather than copying its fields, so the artifact keeps one source of
truth and the two cannot drift.

Revision ID: b1273c009c8e
Revises: 4c7a2e1b9d31
Create Date: 2026-08-12 21:09:47.776974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1273c009c8e'
down_revision: Union[str, Sequence[str], None] = '4c7a2e1b9d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_threads',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('outlier_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlier_id'], ['outliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_threads_channel_id'), 'agent_threads', ['channel_id'], unique=False)
    op.create_index(op.f('ix_agent_threads_outlier_id'), 'agent_threads', ['outlier_id'], unique=False)
    op.create_index(op.f('ix_agent_threads_tenant_id'), 'agent_threads', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_threads_updated_at'), 'agent_threads', ['updated_at'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('thread_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['outlier_diagnoses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['agent_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_diagnosis_id'), 'agent_messages', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_thread_id'), 'agent_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_messages_thread_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_diagnosis_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_threads_updated_at'), table_name='agent_threads')
    op.drop_index(op.f('ix_agent_threads_tenant_id'), table_name='agent_threads')
    op.drop_index(op.f('ix_agent_threads_outlier_id'), table_name='agent_threads')
    op.drop_index(op.f('ix_agent_threads_channel_id'), table_name='agent_threads')
    op.drop_table('agent_threads')
    # ### end Alembic commands ###
