"""baseline schema

Revision ID: d322dfbb1a19
Revises: 
Create Date: 2026-07-21 23:20:42.228016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd322dfbb1a19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('belt', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.Column('base_f80', sa.Float(), nullable=False),
    sa.Column('base_topsize', sa.Float(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('shift', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('t', sa.DateTime(), nullable=False),
    sa.Column('f80', sa.Float(), nullable=False),
    sa.Column('topsize', sa.Float(), nullable=False),
    sa.Column('psd', sa.JSON(), nullable=False),
    sa.Column('color_hsl', sa.String(length=40), nullable=False),
    sa.Column('color_hue', sa.Float(), nullable=False),
    sa.Column('color_sat', sa.Float(), nullable=False),
    sa.Column('color_light', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=True),
    sa.Column('sd_ratio_10_5', sa.Float(), nullable=True),
    sa.Column('video_r', sa.Float(), nullable=True),
    sa.Column('video_g', sa.Float(), nullable=True),
    sa.Column('video_b', sa.Float(), nullable=True),
    sa.Column('sieve_passing_raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_measurements_channel_t', 'measurements', ['channel_id', 't'], unique=False)
    op.create_index(op.f('ix_measurements_t'), 'measurements', ['t'], unique=False)
    op.create_table('outliers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('t', sa.DateTime(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=False),
    sa.Column('sev', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assignee', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('action', sa.String(length=512), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outliers_channel_id'), 'outliers', ['channel_id'], unique=False)
    op.create_index(op.f('ix_outliers_t'), 'outliers', ['t'], unique=False)
    op.create_table('outlier_diagnoses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('outlier_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('root_cause', sa.String(length=2048), nullable=False),
    sa.Column('hypotheses', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(length=1024), nullable=False),
    sa.Column('evidence_summary', sa.String(length=4096), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['outlier_id'], ['outliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outlier_diagnoses_outlier_id'), 'outlier_diagnoses', ['outlier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outlier_diagnoses_outlier_id'), table_name='outlier_diagnoses')
    op.drop_table('outlier_diagnoses')
    op.drop_index(op.f('ix_outliers_t'), table_name='outliers')
    op.drop_index(op.f('ix_outliers_channel_id'), table_name='outliers')
    op.drop_table('outliers')
    op.drop_index(op.f('ix_measurements_t'), table_name='measurements')
    op.drop_index('ix_measurements_channel_t', table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('channels')
    # ### end Alembic commands ###
